### ISSUE TITLE
Support for diagnostic settings & log analytics workspace

### ISSUE THREAD

**Issue by hieunhums** [aztfmod/terraform-azurerm-caf-keyvault-certs#3]
Passthough to terraform-azurerm-caf-keyvault

| Name | Type | Default | Description |
| -- | -- | -- | -- |
| log_analytics_workspace | string | None | (Required) Log Analytics Workspace. |
| diagnostics_map | map | None | (Required) Map with the diagnostics repository information.  |
| diagnostics_settings | object | None | (Required) Map with the diagnostics settings. See the required structure in the following example or in the diagnostics module documentation. |

**Comment by nyuen** [comment]
Closing as KV is created externally and not in the module
